/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

/**
 * This is the main class for the assignment.
 */
public class App {

    private Scanner input;

    private App(Scanner scannerInput) {
        this.input = scannerInput;
    }

    /**
     * Solution to first task.
     */
    public void helloThere() {
        System.out.print("What is your name? ");
        String name = input.nextLine();

        // Remove this and replace with your implementation
        // using the HelloThere class.
        HelloThere another = new HelloThere();
        System.out.println(another.hello(name));
    }

    /**
     * Solution for the second task.
     */
    public void seconds() {
        System.out.print("Enter hours, minutes and seconds: ");
        int hours = input.nextInt();
        int minutes = input.nextInt();
        int seconds = input.nextInt();
        Time another1 = new Time();
        System.out.println(another1.toSeconds(hours, minutes, seconds));
        // HelloThere another = new HelloThere();
        // System.out.println(another.hello(name));
    }
    /**
     * Solution for the third task.
     */
    public void imInaBand() {}

    /**
     * Solution for the fourth task.
     */
    public void bestAlbumsEver() {}

    /**
     * Solution for the fifth task.
     */
    public void workingWithArrays() {}

    /**
     * Starting point of the first assignment.
     *
     * @param args is not used.
     */
    public static void main(String[] args) {
        // we create a scanner object to work with
        // it is advised to create one and only one scanner for a specific stream in the whole
        // application scanners should be closed when you are done and this also closes
        // the underlying stream
        Scanner consoleInput = new Scanner(System.in, "UTF-8");

        App app = new App(consoleInput);

        // Task 1
        app.helloThere();

        // Task 2
        //app.seconds();

        // Task 3
        //app.imInaBand();

        // Task 4
        //app.bestAlbumsEver();

        // Task 5
        //app.workingWithArrays();

        // If you are going for the higher grades you can uncomment the following lines
        // and implement the methods in the GradeC class.
        // GradeC gradeC = new GradeC();
        // gradeC.calculator(consoleInput);
        // gradeC.arrays2D();
        // gradeC.band();

        // now we are exiting the application so time to close the scanner.
        consoleInput.close();
    }
}
